const Allstar = {
  dateNow: '24.08.2020',
  saved: true,
  games: [],
  inputValue: '',
  namePosition: [
    { name: 'Ronaldo', position: 'LF' },
    { name: 'Maradona', position: 'RF' },
    { name: 'Ronaldinho', position: 'RD' },
    { name: 'Zidane', position: 'LD' },
    { name: 'Yashin', position: 'GK' },
    { name: 'Tikhonov', position: 'SUB1' },
    { name: 'Baggio', position: 'SUB3' },
    { name: 'C.Ronaldo', position: 'SUB2' },
    { name: 'Messi', position: 'SUB4' },
  ],
  players: [
    'Ronaldo',
    'Maradona',
    'Ronaldinho',
    'Zidane',
    'Tikhonov',
    'Yashin',
    'Baggio',
    'C.Ronaldo',
    'Messi',
  ],
  playersPosition: [],
  team: 'All-Star',
  inputValueStartPage: '',
  date: [],
  result: '20-1',
  opponent: 'Anyone',
  playersCounter: true,
  playerNameControl: false,
  playerNameControlLength: false,
  Ronaldo: ['LF', 3],
  Maradona: ['RF', 4],
  Ronaldinho: ['RD', 2],
  Zidane: ['LD', 2],
  Yashin: ['GK', -1],
  Tikhonov: ['SUB1', 2],
  Messi: ['SUB4', 2],
  Baggio: ['SUB3', 2],
  'C.Ronaldo': ['SUB2', 3],
};
export default Allstar;
